import type { Metadata } from "next";
import "./globals.css";
import FloatingQuoteButton from "./components/FloatingQuoteButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Footer from "./components/Footer";
import { SmoothScrollProvider } from "./animations/SmoothScrollProvider";
import { MotionProvider } from "./components/MotionProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <MotionProvider>
          <SmoothScrollProvider>
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
            <FloatingQuoteButton />
          </SmoothScrollProvider>
        </MotionProvider>
      </body>
    </html>
  );
}
